name: Generate ASCII Artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v6

        - name: Install Cowsay
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run for cover, I'am Dragon...RAWR " >> dragon.txt
          
        - name: test file exsists
          run: grep -i "dragon.txt"

        - name: Read file
          run: cat dragon.txt

        - name: list Repo files
          run: ls -ltra

            
