name: Exploring variables and secrets

on:
    push

env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: omkarnerale18
        DOCKER_PASSWORD: random

jobs: 
  docker:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: docker build
      run: echo "docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/image:latest"
    
    - name: docker login
      run: echo "docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD"

    - name: docker push
      run: "echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/imagename:latest"


  deploy:
    
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: docker run
      run: echo "docker run -d -p 8000:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/imagename:latest"
    
   
