name: Exploring variables and secrets

on:
    push

env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: omkarnerale18
        DOCKER_PASSWORD: random

jobs: 
  docker:
    
    runs-on: ubuntu-latest
    steps:
    - name: docker build
      run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/image:latest
    
    - name: docker login
      run: docker login --username=$DOCKER_USERNAME --password:$DOCKER_PASSWORD

    - name: docker push
      run: docker push docker.io/dockerusername/imagename:latest


  deploy:
    
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: docker run
      run: docker run -d -p 8000:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/imagename:latest
    
   
